version: "3"
services:
  data-platform-docker-image-builder:
    image : data-platform-docker-image-builder:latest
    privileged: true
    volumes:
      - ${MOUNT_PATH}:/app/mnt
      - .:/app/builder
    working_dir: /app
    tty: true
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_KEY}
